// Code generated by "hl7fetch -pkgdir v21 -root ./genjson -version 2.1"; DO NOT EDIT.

package v21

// Admit a Patient
type ADT_A01 struct {
	HL7 HL7Name `hl7:",name=ADT_A01,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	NK1 *NK1    `hl7:"4,required,display=Next Of Kin"`
	PV1 *PV1    `hl7:"5,required,display=Patient Visit"`
	DG1 *DG1    `hl7:"6,display=Diagnosis"`
}

// Transfer a Patient
type ADT_A02 struct {
	HL7 HL7Name `hl7:",name=ADT_A02,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
}

// Discharge a Patient
type ADT_A03 struct {
	HL7 HL7Name `hl7:",name=ADT_A03,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
}

// Register a Patient
type ADT_A04 struct {
	HL7 HL7Name `hl7:",name=ADT_A04,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	NK1 *NK1    `hl7:"4,required,display=Next Of Kin"`
	PV1 *PV1    `hl7:"5,required,display=Patient Visit"`
	DG1 *DG1    `hl7:"6,display=Diagnosis"`
}

// admit a Patient
type ADT_A05 struct {
	HL7 HL7Name `hl7:",name=ADT_A05,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	NK1 *NK1    `hl7:"4,required,display=Next Of Kin"`
	PV1 *PV1    `hl7:"5,required,display=Patient Visit"`
	DG1 *DG1    `hl7:"6,display=Diagnosis"`
}

// Transfer an Outpatient to Inpatient
type ADT_A06 struct {
	HL7 HL7Name `hl7:",name=ADT_A06,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
}

// Transfer an Inpatient to Outpatient
type ADT_A07 struct {
	HL7 HL7Name `hl7:",name=ADT_A07,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
}

// Update Patient Information
type ADT_A08 struct {
	HL7 HL7Name `hl7:",name=ADT_A08,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	NK1 *NK1    `hl7:"4,required,display=Next Of Kin"`
	PV1 *PV1    `hl7:"5,required,display=Patient Visit"`
	DG1 *DG1    `hl7:"6,display=Diagnosis"`
}

// Patient Departing
type ADT_A09 struct {
	HL7 HL7Name `hl7:",name=ADT_A09,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
	DG1 *DG1    `hl7:"5,display=Diagnosis"`
}

// Patient Arriving
type ADT_A10 struct {
	HL7 HL7Name `hl7:",name=ADT_A10,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
	DG1 *DG1    `hl7:"5,display=Diagnosis"`
}

// Cancel Admit
type ADT_A11 struct {
	HL7 HL7Name `hl7:",name=ADT_A11,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
	DG1 *DG1    `hl7:"5,display=Diagnosis"`
}

// Cancel Transfer
type ADT_A12 struct {
	HL7 HL7Name `hl7:",name=ADT_A12,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
	DG1 *DG1    `hl7:"5,display=Diagnosis"`
}

// Cancel Discharge
type ADT_A13 struct {
	HL7 HL7Name `hl7:",name=ADT_A13,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
	DG1 *DG1    `hl7:"5,display=Diagnosis"`
}

// Pending Admit
type ADT_A14 struct {
	HL7 HL7Name `hl7:",name=ADT_A14,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PD1 *PD1    `hl7:"4,required,display=Patient Demographics"`
	NK1 *NK1    `hl7:"5,required,display=Next Of Kin"`
	PV1 *PV1    `hl7:"6,required,display=Patient Visit"`
	DG1 *DG1    `hl7:"7,display=Diagnosis"`
}

// Pending Transfer
type ADT_A15 struct {
	HL7 HL7Name `hl7:",name=ADT_A15,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
	DG1 *DG1    `hl7:"5,display=Diagnosis"`
}

// Pending Discharge
type ADT_A16 struct {
	HL7 HL7Name `hl7:",name=ADT_A16,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
	DG1 *DG1    `hl7:"5,display=Diagnosis"`
}

// Patient
type ADT_A17_Patient struct {
	HL7 HL7Name `hl7:",name=ADT_A17_Patient,type=tg"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
}

// Swap Patients
type ADT_A17 struct {
	HL7     HL7Name           `hl7:",name=ADT_A17,type=t"`
	MSH     *MSH              `hl7:"1,required,display=Message Header"`
	EVN     *EVN              `hl7:"2,required,display=Event Type"`
	Patient []ADT_A17_Patient `hl7:",required,display=Patient"`
}

// Merge Patient Information
type ADT_A18 struct {
	HL7 HL7Name `hl7:",name=ADT_A18,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	MRG *MRG    `hl7:"4,required,display=Merge Patient Information"`
	PV1 *PV1    `hl7:"5,display=Patient Visit"`
}

// Nursing/Census Application Updates
type ADT_A20 struct {
	HL7 HL7Name `hl7:",name=ADT_A20,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	NPU *NPU    `hl7:"3,required,display=Non-patient Update"`
}

// A Patient Goes On A "Leave Of Absence"
type ADT_A21 struct {
	HL7 HL7Name `hl7:",name=ADT_A21,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
}

// A Patient Returns From A "Leave Of Absence"
type ADT_A22 struct {
	HL7 HL7Name `hl7:",name=ADT_A22,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
}

// Delete a Patient Record
type ADT_A23 struct {
	HL7 HL7Name `hl7:",name=ADT_A23,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,required,display=Patient Visit"`
}

// Create a Patient Link Transaction
type ADT_A24 struct {
	HL7  HL7Name `hl7:",name=ADT_A24,type=t"`
	MSH  *MSH    `hl7:"1,required,display=Message Header"`
	EVN  *EVN    `hl7:"2,required,display=Event Type"`
	PID  *PID    `hl7:"3,required,display=Patient Identification"`
	PV1  *PV1    `hl7:"4,required,display=Patient Visit"`
	PID2 *PID    `hl7:"5,required,display=Patient Identification"`
}

// Visit
type BAR_P01_Visit struct {
	HL7 HL7Name `hl7:",name=BAR_P01_Visit,type=tg"`
	PV1 *PV1    `hl7:"4,display=Patient Visit"`
	DG1 []DG1   `hl7:"5,display=Diagnosis"`
	PR1 []PR1   `hl7:"6,display=Procedures"`
	GT1 []GT1   `hl7:"7,display=Guarantor"`
	NK1 []NK1   `hl7:"8,display=Next Of Kin"`
	IN1 []IN1   `hl7:"9,display=Insurance"`
	ACC *ACC    `hl7:"10,display=Accident"`
	UB1 *UB1    `hl7:"11,display=Ub82 Data"`
}

// Add and Update Patient Accounts
type BAR_P01 struct {
	HL7   HL7Name         `hl7:",name=BAR_P01,type=t"`
	MSH   *MSH            `hl7:"1,required,display=Message Header"`
	EVN   *EVN            `hl7:"2,required,display=Event Type"`
	PID   *PID            `hl7:"3,required,display=Patient Identification"`
	Visit []BAR_P01_Visit `hl7:",required,display=Visit"`
}

// Patient
type BAR_P02_Patient struct {
	HL7 HL7Name `hl7:",name=BAR_P02_Patient,type=tg"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,display=Patient Visit"`
}

// Purge Patient Accounts
type BAR_P02 struct {
	HL7     HL7Name           `hl7:",name=BAR_P02,type=t"`
	MSH     *MSH              `hl7:"1,required,display=Message Header"`
	EVN     *EVN              `hl7:"2,required,display=Event Type"`
	Patient []BAR_P02_Patient `hl7:",required,display=Patient"`
}

// Post Detail Financial Transactions
type DFT_P03 struct {
	HL7 HL7Name `hl7:",name=DFT_P03,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	EVN *EVN    `hl7:"2,required,display=Event Type"`
	PID *PID    `hl7:"3,required,display=Patient Identification"`
	PV1 *PV1    `hl7:"4,display=Patient Visit"`
	FT1 []FT1   `hl7:"5,display=Financial Transaction"`
}

// Deferred Response to A Query
type DSR_Q03 struct {
	HL7 HL7Name `hl7:",name=DSR_Q03,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	QRD *QRD    `hl7:"2,required,display=Query Definition"`
	QRF *QRF    `hl7:"3,display=Query Filter"`
	DSP []DSP   `hl7:"4,required,display=Display Data"`
	DSC *DSC    `hl7:"5,required,display=Continuation Pointer"`
}

// Patient
type ORM_O01_Patient struct {
	HL7   HL7Name         `hl7:",name=ORM_O01_Patient,type=tg"`
	PID   *PID            `hl7:"3,required,display=Patient Identification"`
	NTE   []NTE           `hl7:"4,display=Notes And Comments"`
	PV1   *PV1            `hl7:"5,display=Patient Visit"`
	Order []ORM_O01_Order `hl7:",required,display=Order"`
}

// Order
type ORM_O01_Order struct {
	HL7         HL7Name              `hl7:",name=ORM_O01_Order,type=tg"`
	ORC         *ORC                 `hl7:"6,required,display=Common Order"`
	Orderdetail *ORM_O01_Orderdetail `hl7:",display=Order_detail"`
}

// Orderdetail
type ORM_O01_Orderdetail struct {
	HL7  HL7Name `hl7:",name=ORM_O01_Orderdetail,type=tg"`
	OBR  *OBR    `hl7:"7,required,display=Observation Request"`
	NTE  []NTE   `hl7:"8,display=Notes And Comments"`
	OBX  []OBX   `hl7:"9,display=Result"`
	NTE2 []NTE   `hl7:"10,display=Notes And Comments"`
	BLG  *BLG    `hl7:"11,display=Billing"`
}

// Order Message
type ORM_O01 struct {
	HL7     HL7Name          `hl7:",name=ORM_O01,type=t"`
	MSH     *MSH             `hl7:"1,required,display=Message Header"`
	NTE     []NTE            `hl7:"2,display=Notes And Comments"`
	Patient *ORM_O01_Patient `hl7:",display=Patient"`
}

// Patient
type ORR_O02_Patient struct {
	HL7   HL7Name         `hl7:",name=ORR_O02_Patient,type=tg"`
	PID   *PID            `hl7:"4,display=Patient Identification"`
	NTE   []NTE           `hl7:"5,display=Notes And Comments"`
	Order []ORR_O02_Order `hl7:",required,display=Order"`
}

// Order
type ORR_O02_Order struct {
	HL7         HL7Name              `hl7:",name=ORR_O02_Order,type=tg"`
	ORC         *ORC                 `hl7:"6,required,display=Common Order"`
	Orderdetail *ORR_O02_Orderdetail `hl7:",display=Order_detail"`
}

// Orderdetail
type ORR_O02_Orderdetail struct {
	HL7 HL7Name `hl7:",name=ORR_O02_Orderdetail,type=tg"`
	OBR *OBR    `hl7:"7,required,display=Observation Request"`
	NTE []NTE   `hl7:"8,display=Notes And Comments"`
}

// Respone Message
type ORR_O02 struct {
	HL7     HL7Name          `hl7:",name=ORR_O02,type=t"`
	MSH     *MSH             `hl7:"1,required,display=Message Header"`
	MSA     *MSA             `hl7:"2,required,display=Message Acknowledgment"`
	NTE     []NTE            `hl7:"3,display=Notes And Comments"`
	Patient *ORR_O02_Patient `hl7:",display=Patient"`
}

// Patientresult
type ORU_R01_Patientresult struct {
	HL7     HL7Name          `hl7:",name=ORU_R01_Patientresult,type=tg"`
	Patient *ORU_R01_Patient `hl7:",display=Patient"`
}

// Patient
type ORU_R01_Patient struct {
	HL7              HL7Name                    `hl7:",name=ORU_R01_Patient,type=tg"`
	PID              *PID                       `hl7:"2,required,display=Patient Identification"`
	NTE              []NTE                      `hl7:"3,display=Notes And Comments"`
	PV1              *PV1                       `hl7:"4,display=Patient Visit"`
	Orderobservation []ORU_R01_Orderobservation `hl7:",required,display=Order_observation"`
}

// Orderobservation
type ORU_R01_Orderobservation struct {
	HL7         HL7Name               `hl7:",name=ORU_R01_Orderobservation,type=tg"`
	ORC         *ORC                  `hl7:"5,display=Common Order"`
	OBR         *OBR                  `hl7:"6,required,display=Observation Request"`
	NTE         []NTE                 `hl7:"7,display=Notes And Comments"`
	Observation []ORU_R01_Observation `hl7:",required,display=Observation"`
}

// Observation
type ORU_R01_Observation struct {
	HL7 HL7Name `hl7:",name=ORU_R01_Observation,type=tg"`
	OBX *OBX    `hl7:"8,display=Result"`
	NTE []NTE   `hl7:"9,display=Notes And Comments"`
	DSC *DSC    `hl7:"10,display=Continuation Pointer"`
}

// Unsolicited transmission of requested Obersvation
type ORU_R01 struct {
	HL7           HL7Name                 `hl7:",name=ORU_R01,type=t"`
	MSH           *MSH                    `hl7:"1,required,display=Message Header"`
	Patientresult []ORU_R01_Patientresult `hl7:",required,display=Patient_result"`
}

// Patientresult
type ORU_R03_Patientresult struct {
	HL7     HL7Name          `hl7:",name=ORU_R03_Patientresult,type=tg"`
	Patient *ORU_R03_Patient `hl7:",display=Patient"`
}

// Patient
type ORU_R03_Patient struct {
	HL7              HL7Name                    `hl7:",name=ORU_R03_Patient,type=tg"`
	PID              *PID                       `hl7:"2,required,display=Patient Identification"`
	NTE              []NTE                      `hl7:"3,display=Notes And Comments"`
	PV1              *PV1                       `hl7:"4,display=Patient Visit"`
	Orderobservation []ORU_R03_Orderobservation `hl7:",required,display=Order_observation"`
}

// Orderobservation
type ORU_R03_Orderobservation struct {
	HL7         HL7Name               `hl7:",name=ORU_R03_Orderobservation,type=tg"`
	ORC         *ORC                  `hl7:"5,display=Common Order"`
	OBR         *OBR                  `hl7:"6,required,display=Observation Request"`
	NTE         []NTE                 `hl7:"7,display=Notes And Comments"`
	Observation []ORU_R03_Observation `hl7:",required,display=Observation"`
}

// Observation
type ORU_R03_Observation struct {
	HL7 HL7Name `hl7:",name=ORU_R03_Observation,type=tg"`
	OBX *OBX    `hl7:"8,display=Result"`
	NTE []NTE   `hl7:"9,display=Notes And Comments"`
	DSC *DSC    `hl7:"10,display=Continuation Pointer"`
}

// Display oriented results, queyr/unsol. update
type ORU_R03 struct {
	HL7           HL7Name                 `hl7:",name=ORU_R03,type=t"`
	MSH           *MSH                    `hl7:"1,required,display=Message Header"`
	Patientresult []ORU_R03_Patientresult `hl7:",required,display=Patient_result"`
}

// Patient Query
type QRY_A19 struct {
	HL7 HL7Name `hl7:",name=QRY_A19,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	QRD *QRD    `hl7:"2,required,display=Query Definition"`
}

// A Query is Made for Immediate Response
type QRY_Q01 struct {
	HL7 HL7Name `hl7:",name=QRY_Q01,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	QRD *QRD    `hl7:"2,required,display=Query Definition"`
	QRF *QRF    `hl7:"3,display=Query Filter"`
	DSC *DSC    `hl7:"4,required,display=Continuation Pointer"`
}

// A Query is Sent for Deferred Response
type QRY_Q02 struct {
	HL7 HL7Name `hl7:",name=QRY_Q02,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	QRD *QRD    `hl7:"2,required,display=Query Definition"`
	QRF *QRF    `hl7:"3,display=Query Filter"`
	DSC *DSC    `hl7:"4,required,display=Continuation Pointer"`
}

// Unsolicited Updates, ODM Message, Trigger Event Q05
type UDM_Q05 struct {
	HL7 HL7Name `hl7:",name=UDM_Q05,type=t"`
	MSH *MSH    `hl7:"1,required,display=Message Header"`
	URD *URD    `hl7:"2,required,display=Results/update Definition"`
	URS *URS    `hl7:"3,display=Unsolicited Selection"`
	DSP []DSP   `hl7:"4,required,display=Display Data"`
	DSC *DSC    `hl7:"5,required,display=Continuation Pointer"`
}
