// Code generated by "hl7fetch -pkgdir h21 -root ./genjson -version 2.1"; DO NOT EDIT.

package h21

import "time"

// Address
type AD = string

// Coded Element
type CE struct {
	HL7                         HL7Name `hl7:",name=CE,len=0,type=d"`
	Identifier                  ID      `hl7:"1,display=Identifier"`
	Text                        ST      `hl7:"2,display=Text"`
	NameOfCodingSystem          ST      `hl7:"3,display=Name Of Coding System"`
	AlternateIdentifier         ST      `hl7:"4,display=Alternate Identifier"`
	AlternateText               ST      `hl7:"5,display=Alternate Text"`
	NameOfAlternateCodingSystem ST      `hl7:"6,display=Name Of Alternate Coding System"`
}

// Composite Id With Check Digit
type CK = string

//
type CM = string

// Composite Id Number And Name
type CN = string

// Composite Quantity With Units
type CQ = string

// Date
type DT = time.Time

// Coded Value
type ID = string

// Numeric
type NM = string

// Person Name
type PN = string

// Set Id
type SI = string

// String Data
type ST = string

// Telephone Number
type TN = string

// Time Stamp
type TS = time.Time

// Text Data
type TX = string
