// Code generated by "hl7fetch -pkgdir h210 -root ./genjson -version 2.1"; DO NOT EDIT.

package h210

import (
	"fmt"
	"reflect"
)

// Accident
type ACC struct {
	HL7              HL7Name `hl7:",name=ACC,type=s"`
	AccidentDateTime TS      `hl7:"1,len=19,format=YMDHMS,display=Accident Date/Time"`
	AccidentCode     ID      `hl7:"2,len=2,table=0050,display=Accident Code"`
	AccidentLocation ST      `hl7:"3,len=25,display=Accident Location"`
}

// Addendum
type ADD struct {
	HL7                         HL7Name `hl7:",name=ADD,type=s"`
	AddendumContinuationPointer ST      `hl7:"1,len=60,display=Addendum Continuation Pointer"`
}

// Batch Header
type BHS struct {
	HL7                       HL7Name `hl7:",name=BHS,type=s"`
	BatchFieldSeparator       ST      `hl7:"1,required,len=1,display=Batch Field Separator"`
	BatchEncodingCharacters   ST      `hl7:"2,required,len=3,display=Batch Encoding Characters"`
	BatchSendingApplication   ST      `hl7:"3,len=15,display=Batch Sending Application"`
	BatchSendingFacility      ST      `hl7:"4,len=20,display=Batch Sending Facility"`
	BatchReceivingApplication ST      `hl7:"5,len=15,display=Batch Receiving Application"`
	BatchReceivingFacility    ST      `hl7:"6,len=20,display=Batch Receiving Facility"`
	BatchCreationDateTime     TS      `hl7:"7,len=19,format=YMDHMS,display=Batch Creation Date/Time"`
	BatchSecurity             ST      `hl7:"8,len=40,display=Batch Security"`
	BatchNameIDType           ST      `hl7:"9,len=20,display=Batch Name/Id/Type"`
	BatchComment              ST      `hl7:"10,len=80,display=Batch Comment"`
	BatchControlID            ST      `hl7:"11,len=20,display=Batch Control Id"`
	ReferenceBatchControlID   ST      `hl7:"12,len=20,display=Reference Batch Control Id"`
}

// Billing
type BLG struct {
	HL7          HL7Name `hl7:",name=BLG,type=s"`
	WhenToCharge CM      `hl7:"1,len=15,table=0100,display=When To Charge"`
	ChargeType   ID      `hl7:"2,len=50,table=0122,display=Charge Type"`
	AccountID    CM      `hl7:"3,len=100,display=Account Id"`
}

// Batch Trailer
type BTS struct {
	HL7               HL7Name `hl7:",name=BTS,type=s"`
	BatchMessageCount ST      `hl7:"1,len=10,display=Batch Message Count"`
	BatchComment      ST      `hl7:"2,len=80,display=Batch Comment"`
	BatchTotals       CM      `hl7:"3,len=100,display=Batch Totals"`
}

// Diagnosis
type DG1 struct {
	HL7                     HL7Name `hl7:",name=DG1,type=s"`
	SetIDDiagnosis          SI      `hl7:"1,required,len=4,display=Set Id - Diagnosis"`
	DiagnosisCodingMethod   ID      `hl7:"2,required,len=2,table=0053,display=Diagnosis Coding Method"`
	DiagnosisCode           ID      `hl7:"3,len=8,table=0051,display=Diagnosis Code"`
	DiagnosisDescription    ST      `hl7:"4,len=40,display=Diagnosis Description"`
	DiagnosisDateTime       TS      `hl7:"5,len=19,format=YMDHMS,display=Diagnosis Date/Time"`
	DiagnosisDrgType        ID      `hl7:"6,required,len=2,table=0052,display=Diagnosis/Drg Type"`
	MajorDiagnosticCategory ST      `hl7:"7,len=4,table=0118,display=Major Diagnostic Category"`
	DiagnosticRelatedGroup  ID      `hl7:"8,len=4,table=0055,display=Diagnostic Related Group"`
	DrgApprovalIndicator    ID      `hl7:"9,len=2,display=Drg Approval Indicator"`
	DrgGrouperReviewCode    ID      `hl7:"10,len=2,table=0056,display=Drg Grouper Review Code"`
	OutlierType             ID      `hl7:"11,len=2,table=0083,display=Outlier Type"`
	OutlierDays             NM      `hl7:"12,len=3,display=Outlier Days"`
	OutlierCost             NM      `hl7:"13,len=12,display=Outlier Cost"`
	GrouperVersionAndType   ST      `hl7:"14,len=4,display=Grouper Version And Type"`
}

// Continuation Pointer
type DSC struct {
	HL7                 HL7Name `hl7:",name=DSC,type=s"`
	ContinuationPointer ST      `hl7:"1,len=60,display=Continuation Pointer"`
}

// Display Data
type DSP struct {
	HL7               HL7Name `hl7:",name=DSP,type=s"`
	SetIDDisplayData  SI      `hl7:"1,len=4,display=Set Id - Display Data"`
	DisplayLevel      SI      `hl7:"2,len=4,display=Display Level"`
	DataLine          TX      `hl7:"3,required,len=300,display=Data Line"`
	LogicalBreakPoint ST      `hl7:"4,len=2,display=Logical Break Point"`
	ResultID          TX      `hl7:"5,len=20,display=Result Id"`
}

// Event Type
type EVN struct {
	HL7                  HL7Name `hl7:",name=EVN,type=s"`
	EventTypeCode        ID      `hl7:"1,required,len=3,table=0003,display=Event Type Code"`
	DateTimeOfEvent      TS      `hl7:"2,required,len=19,format=YMDHMS,display=Date/Time Of Event"`
	DateTimePlannedEvent TS      `hl7:"3,len=19,format=YMDHMS,display=Date/Time Planned Event"`
	EventReasonCode      ID      `hl7:"4,len=3,table=0062,display=Event Reason Code"`
}

// File Header
type FHS struct {
	HL7                      HL7Name `hl7:",name=FHS,type=s"`
	FileFieldSeparator       ST      `hl7:"1,required,len=1,display=File Field Separator"`
	FileEncodingCharacters   ST      `hl7:"2,required,len=4,display=File Encoding Characters"`
	FileSendingApplication   ST      `hl7:"3,len=15,display=File Sending Application"`
	FileSendingFacility      ST      `hl7:"4,len=20,display=File Sending Facility"`
	FileReceivingApplication ST      `hl7:"5,len=15,display=File Receiving Application"`
	FileReceivingFacility    ST      `hl7:"6,len=20,display=File Receiving Facility"`
	DateTimeOfFileCreation   TS      `hl7:"7,len=19,format=YMDHMS,display=Date/Time Of File Creation"`
	FileSecurity             ST      `hl7:"8,len=40,display=File Security"`
	FileNameID               ST      `hl7:"9,len=20,display=File Name/Id"`
	FileHeaderComment        ST      `hl7:"10,len=80,display=File Header Comment"`
	FileControlID            ST      `hl7:"11,len=20,display=File Control Id"`
	ReferenceFileControlID   ST      `hl7:"12,len=20,display=Reference File Control Id"`
}

// Financial Transaction
type FT1 struct {
	HL7                       HL7Name `hl7:",name=FT1,type=s"`
	SetIDFinancialTransaction SI      `hl7:"1,len=4,display=Set Id - Financial Transaction"`
	TransactionID             ST      `hl7:"2,len=12,display=Transaction Id"`
	TransactionBatchID        ST      `hl7:"3,len=5,display=Transaction Batch Id"`
	TransactionDate           DT      `hl7:"4,required,len=8,format=YMD,display=Transaction Date"`
	TransactionPostingDate    DT      `hl7:"5,len=8,format=YMD,display=Transaction Posting Date"`
	TransactionType           ID      `hl7:"6,required,len=8,table=0017,display=Transaction Type"`
	TransactionCode           ID      `hl7:"7,required,len=20,table=0096,display=Transaction Code"`
	TransactionDescription    ST      `hl7:"8,len=40,display=Transaction Description"`
	TransactionDescriptionAlt ST      `hl7:"9,len=40,display=Transaction Description - Alt"`
	TransactionAmountExtended NM      `hl7:"10,len=12,display=Transaction Amount - Extended"`
	TransactionQuantity       NM      `hl7:"11,len=4,display=Transaction Quantity"`
	TransactionAmountUnit     NM      `hl7:"12,len=12,display=Transaction Amount - Unit"`
	DepartmentCode            ST      `hl7:"13,len=16,table=0049,display=Department Code"`
	InsurancePlanID           ID      `hl7:"14,len=8,table=0072,display=Insurance Plan Id"`
	InsuranceAmount           NM      `hl7:"15,len=12,display=Insurance Amount"`
	PatientLocation           ST      `hl7:"16,len=12,table=0079,display=Patient Location"`
	FeeSchedule               ID      `hl7:"17,len=1,table=0024,display=Fee Schedule"`
	PatientType               ID      `hl7:"18,len=2,table=0018,display=Patient Type"`
	DiagnosisCode             ID      `hl7:"19,len=8,table=0051,display=Diagnosis Code"`
	PerformedByCode           CN      `hl7:"20,len=60,table=0084,display=Performed By Code"`
	OrderedByCode             CN      `hl7:"21,len=60,display=Ordered By Code"`
	UnitCost                  NM      `hl7:"22,len=12,display=Unit Cost"`
}

// File Trailer
type FTS struct {
	HL7                HL7Name `hl7:",name=FTS,type=s"`
	FileBatchCount     ST      `hl7:"1,len=10,display=File Batch Count"`
	FileTrailerComment ST      `hl7:"2,len=80,display=File Trailer Comment"`
}

// Guarantor
type GT1 struct {
	HL7                       HL7Name `hl7:",name=GT1,type=s"`
	SetIDGuarantor            SI      `hl7:"1,required,len=4,display=Set Id - Guarantor"`
	GuarantorNumber           ID      `hl7:"2,len=20,display=Guarantor Number"`
	GuarantorName             PN      `hl7:"3,required,len=48,display=Guarantor Name"`
	GuarantorSpouseName       PN      `hl7:"4,len=48,display=Guarantor Spouse Name"`
	GuarantorAddress          AD      `hl7:"5,len=106,display=Guarantor Address"`
	GuarantorPhNumHome        TN      `hl7:"6,len=40,display=Guarantor Ph. Num.- Home"`
	GuarantorPhNumBusiness    TN      `hl7:"7,len=40,display=Guarantor Ph. Num-business"`
	GuarantorDateOfBirth      DT      `hl7:"8,len=8,format=YMD,display=Guarantor Date Of Birth"`
	GuarantorSex              ID      `hl7:"9,len=1,table=0001,display=Guarantor Sex"`
	GuarantorType             ID      `hl7:"10,len=2,table=0068,display=Guarantor Type"`
	GuarantorRelationship     ID      `hl7:"11,len=2,table=0063,display=Guarantor Relationship"`
	GuarantorSsn              ST      `hl7:"12,len=11,display=Guarantor Ssn"`
	GuarantorDateBegin        DT      `hl7:"13,len=8,format=YMD,display=Guarantor Date - Begin"`
	GuarantorDateEnd          DT      `hl7:"14,len=8,format=YMD,display=Guarantor Date - End"`
	GuarantorPriority         NM      `hl7:"15,len=2,display=Guarantor Priority"`
	GuarantorEmployerName     ST      `hl7:"16,len=45,display=Guarantor Employer Name"`
	GuarantorEmployerAddress  AD      `hl7:"17,len=106,display=Guarantor Employer Address"`
	GuarantorEmployPhone      TN      `hl7:"18,len=40,display=Guarantor Employ Phone #"`
	GuarantorEmployeeIDNum    ST      `hl7:"19,len=20,display=Guarantor Employee Id Num"`
	GuarantorEmploymentStatus ID      `hl7:"20,len=2,table=0066,display=Guarantor Employment Status"`
}

// Insurance
type IN1 struct {
	HL7                           HL7Name `hl7:",name=IN1,type=s"`
	SetIDInsurance                SI      `hl7:"1,required,len=4,display=Set Id - Insurance"`
	InsurancePlanID               ID      `hl7:"2,required,len=8,table=0072,display=Insurance Plan Id"`
	InsuranceCompanyID            ST      `hl7:"3,required,len=6,display=Insurance Company Id"`
	InsuranceCompanyName          ST      `hl7:"4,len=45,display=Insurance Company Name"`
	InsuranceCompanyAddress       AD      `hl7:"5,len=106,display=Insurance Company Address"`
	InsuranceCoContactPers        PN      `hl7:"6,len=48,display=Insurance Co. Contact Pers"`
	InsuranceCoPhoneNumber        TN      `hl7:"7,len=40,display=Insurance Co Phone Number"`
	GroupNumber                   ST      `hl7:"8,len=12,display=Group Number"`
	GroupName                     ST      `hl7:"9,len=35,display=Group Name"`
	InsuredsGroupEmpID            ST      `hl7:"10,len=12,display=Insured's Group Emp. Id"`
	InsuredsGroupEmpName          ST      `hl7:"11,len=45,display=Insured's Group Emp. Name"`
	PlanEffectiveDate             DT      `hl7:"12,len=8,format=YMD,display=Plan Effective Date"`
	PlanExpirationDate            DT      `hl7:"13,len=8,format=YMD,display=Plan Expiration Date"`
	AuthorizationInformation      ST      `hl7:"14,len=55,display=Authorization Information"`
	PlanType                      ID      `hl7:"15,len=2,table=0086,display=Plan Type"`
	NameOfInsured                 PN      `hl7:"16,len=48,display=Name Of Insured"`
	InsuredsRelationshipToPatient ID      `hl7:"17,len=2,table=0063,display=Insured's Relationship To Patient"`
	InsuredsDateOfBirth           DT      `hl7:"18,len=8,format=YMD,display=Insured's Date Of Birth"`
	InsuredsAddress               AD      `hl7:"19,len=106,display=Insured's Address"`
	AssignmentOfBenefits          ID      `hl7:"20,len=2,display=Assignment Of Benefits"`
	CoordinationOfBenefits        ID      `hl7:"21,len=2,display=Coordination Of Benefits"`
	CoordOfBenPriority            ST      `hl7:"22,len=2,display=Coord Of Ben. Priority"`
	NoticeOfAdmissionCode         ID      `hl7:"23,len=2,table=0081,display=Notice Of Admission Code"`
	NoticeOfAdmissionDate         DT      `hl7:"24,len=8,format=YMD,display=Notice Of Admission Date"`
	RptOfEligibilityCode          ID      `hl7:"25,len=2,table=0094,display=Rpt Of Eligibility Code"`
	RptOfEligibilityDate          DT      `hl7:"26,len=8,format=YMD,display=Rpt Of Eligibility Date"`
	ReleaseInformationCode        ID      `hl7:"27,len=2,table=0093,display=Release Information Code"`
	PreAdmitCertPac               ST      `hl7:"28,len=15,display=Pre-admit Cert. (pac)"`
	VerificationDate              DT      `hl7:"29,len=8,format=YMD,display=Verification Date"`
	VerificationBy                CM      `hl7:"30,len=60,display=Verification By"`
	TypeOfAgreementCode           ID      `hl7:"31,len=2,table=0098,display=Type Of Agreement Code"`
	BillingStatus                 ID      `hl7:"32,len=2,table=0022,display=Billing Status"`
	LifetimeReserveDays           NM      `hl7:"33,len=4,display=Lifetime Reserve Days"`
	DelayBeforeLRDay              NM      `hl7:"34,len=4,display=Delay Before L. R. Day"`
	CompanyPlanCode               ST      `hl7:"35,len=8,table=0042,display=Company Plan Code"`
	PolicyNumber                  ST      `hl7:"36,len=15,display=Policy Number"`
	PolicyDeductible              NM      `hl7:"37,len=12,display=Policy Deductible"`
	PolicyLimitAmount             NM      `hl7:"38,len=12,display=Policy Limit - Amount"`
	PolicyLimitDays               NM      `hl7:"39,len=4,display=Policy Limit - Days"`
	RoomRateSemiPrivate           NM      `hl7:"40,len=12,display=Room Rate - Semi-private"`
	RoomRatePrivate               NM      `hl7:"41,len=12,display=Room Rate - Private"`
	InsuredsEmploymentStatus      ID      `hl7:"42,len=1,table=0066,display=Insured's Employment Status"`
	InsuredsSex                   ID      `hl7:"43,len=1,table=0001,display=Insured's Sex"`
	InsuredsEmployerAddress       AD      `hl7:"44,len=106,display=Insured's Employer Address"`
}

// Merge Patient Information
type MRG struct {
	HL7                       HL7Name `hl7:",name=MRG,type=s"`
	PriorPatientIDInternal    CK      `hl7:"1,required,len=16,display=Prior Patient Id - Internal"`
	PriorAlternatePatientID   CK      `hl7:"2,len=16,display=Prior Alternate Patient Id"`
	PriorPatientAccountNumber CK      `hl7:"3,len=20,display=Prior Patient Account Number"`
}

// Message Acknowledgment
type MSA struct {
	HL7                       HL7Name `hl7:",name=MSA,type=s"`
	AcknowledgmentCode        ID      `hl7:"1,required,len=2,table=0008,display=Acknowledgment Code"`
	MessageControlID          ST      `hl7:"2,required,len=20,display=Message Control Id"`
	TextMessage               ST      `hl7:"3,len=80,display=Text Message"`
	ExpectedSequenceNumber    NM      `hl7:"4,len=15,display=Expected Sequence Number"`
	DelayedAcknowledgmentType ID      `hl7:"5,len=1,table=0102,display=Delayed Acknowledgment Type"`
}

// Message Header
type MSH struct {
	HL7                  HL7Name `hl7:",name=MSH,type=s"`
	FieldSeparator       ST      `hl7:"1,noescape,fieldsep,omit,required,len=1,display=Field Separator"`
	EncodingCharacters   ST      `hl7:"2,noescape,fieldchars,required,len=4,display=Encoding Characters"`
	SendingApplication   ST      `hl7:"3,len=15,display=Sending Application"`
	SendingFacility      ST      `hl7:"4,len=20,display=Sending Facility"`
	ReceivingApplication ST      `hl7:"5,len=15,display=Receiving Application"`
	ReceivingFacility    ST      `hl7:"6,len=30,display=Receiving Facility"`
	DateTimeOfMessage    TS      `hl7:"7,len=19,format=YMDHMS,display=Date/Time Of Message"`
	Security             ST      `hl7:"8,len=40,display=Security"`
	MessageType          ID      `hl7:"9,required,len=7,table=0076,display=Message Type"`
	MessageControlID     ST      `hl7:"10,required,len=20,display=Message Control Id"`
	ProcessingID         ID      `hl7:"11,required,len=1,table=0103,display=Processing Id"`
	VersionID            NM      `hl7:"12,required,len=8,table=0104,display=Version Id"`
	SequenceNumber       NM      `hl7:"13,len=15,display=Sequence Number"`
	ContinuationPointer  ST      `hl7:"14,len=180,display=Continuation Pointer"`
}

// Next Of Kin
type NK1 struct {
	HL7                   HL7Name `hl7:",name=NK1,type=s"`
	SetIDNextOfKin        SI      `hl7:"1,required,len=4,display=Set Id - Next Of Kin"`
	NextOfKinName         PN      `hl7:"2,len=48,display=Next Of Kin Name"`
	NextOfKinRelationship ST      `hl7:"3,len=15,table=0063,display=Next Of Kin Relationship"`
	NextOfKinAddress      AD      `hl7:"4,len=106,display=Next Of Kin - Address"`
	NextOfKinPhoneNumber  []TN    `hl7:"5,len=40,display=Next Of Kin - Phone Number"`
}

// Non-patient Update
type NPU struct {
	HL7         HL7Name `hl7:",name=NPU,type=s"`
	BedLocation ID      `hl7:"1,required,len=12,table=0079,display=Bed Location"`
	BedStatus   ID      `hl7:"2,len=1,table=0116,display=Bed Status"`
}

// Notes And Comments
type NTE struct {
	HL7                   HL7Name `hl7:",name=NTE,type=s"`
	SetIDNotesAndComments SI      `hl7:"1,len=4,display=Set Id - Notes And Comments"`
	SourceOfComment       ID      `hl7:"2,len=8,table=0105,display=Source Of Comment"`
	Comment               []TX    `hl7:"3,required,len=120,display=Comment"`
}

// Observation Request
type OBR struct {
	HL7                        HL7Name `hl7:",name=OBR,type=s"`
	SetIDObservationRequest    SI      `hl7:"1,len=4,display=Set Id - Observation Request"`
	PlacerOrder                CM      `hl7:"2,len=75,display=Placer Order #"`
	FillerOrder                CM      `hl7:"3,len=75,display=Filler Order #"`
	UniversalServiceIdent      CE      `hl7:"4,required,len=200,display=Universal Service Ident."`
	Priority                   ST      `hl7:"5,len=2,display=Priority"`
	RequestedDateTime          TS      `hl7:"6,len=19,format=YMDHMS,display=Requested Date-time"`
	ObservationDateTime        TS      `hl7:"7,required,len=19,format=YMDHMS,display=Observation Date/Time"`
	ObservationEndDateTime     TS      `hl7:"8,required,len=19,format=YMDHMS,display=Observation End Date/Time"`
	CollectionVolume           CQ      `hl7:"9,required,len=20,table=0036,display=Collection Volume"`
	CollectorIdentifier        []CN    `hl7:"10,len=60,display=Collector Identifier"`
	SpecimenActionCode         ST      `hl7:"11,len=1,table=0065,display=Specimen Action Code"`
	DangerCode                 CM      `hl7:"12,len=60,table=0047,display=Danger Code"`
	RelevantClinicalInfo       ST      `hl7:"13,len=300,display=Relevant Clinical Info."`
	SpecimenReceivedDateTime   TS      `hl7:"14,required,len=19,format=YMDHMS,display=Specimen Received Date/Time"`
	SpecimenSource             CM      `hl7:"15,len=300,table=0070,display=Specimen Source"`
	OrderingProvider           []CN    `hl7:"16,len=60,table=0010,display=Ordering Provider"`
	OrderCallBackPhoneNum      []TN    `hl7:"17,max=2,len=40,display=Order Call-back Phone Num"`
	PlacersField1              ST      `hl7:"18,len=60,display=Placers Field #1"`
	PlacersField2              ST      `hl7:"19,len=60,display=Placers Field #2"`
	FillersField1              ST      `hl7:"20,len=60,display=Fillers Field #1"`
	FillersField2              ST      `hl7:"21,len=60,display=Fillers Field #2"`
	ResultsRptStatusChngDateT  TS      `hl7:"22,required,len=19,format=YMDHMS,display=Results Rpt/Status Chng - Date/T"`
	ChargeToPractice           CM      `hl7:"23,len=40,display=Charge To Practice"`
	DiagnosticServSectID       ID      `hl7:"24,len=10,table=0074,display=Diagnostic Serv Sect Id"`
	ResultStatus               ID      `hl7:"25,len=1,table=0123,display=Result Status"`
	LinkedResults              *CE     `hl7:"26,len=200,display=Linked Results"`
	QuantityTiming             []CM    `hl7:"27,len=200,display=Quantity/Timing"`
	ResultCopiesTo             []CN    `hl7:"28,max=5,len=80,display=Result Copies To"`
	ParentAccession            CM      `hl7:"29,len=150,display=Parent Accession #"`
	TransportationMode         ID      `hl7:"30,len=20,table=0124,display=Transportation Mode"`
	ReasonForStudy             []CE    `hl7:"31,len=300,display=Reason For Study"`
	PrincipalResultInterpreter CN      `hl7:"32,len=60,display=Principal Result Interpreter"`
	AssistantResultInterpreter CN      `hl7:"33,len=60,display=Assistant Result Interpreter"`
	Technician                 CN      `hl7:"34,len=60,display=Technician"`
	Transcriptionist           CN      `hl7:"35,len=60,display=Transcriptionist"`
	ScheduledDateTime          TS      `hl7:"36,len=19,format=YMDHMS,display=Scheduled - Date/Time"`
}

// Result
type OBX struct {
	HL7                     HL7Name `hl7:",name=OBX,type=s"`
	SetIDObservationSimple  SI      `hl7:"1,len=4,display=Set Id - Observation Simple"`
	ValueType               ID      `hl7:"2,len=2,table=0125,display=Value Type"`
	ObservationIdentifier   CE      `hl7:"3,required,len=80,display=Observation Identifier"`
	ObservationSubID        NM      `hl7:"4,len=20,display=Observation Sub-id"`
	ObservationResults      ST      `hl7:"5,required,len=65,display=Observation Results"`
	Units                   ID      `hl7:"6,len=20,display=Units"`
	ReferencesRange         ST      `hl7:"7,len=60,display=References Range"`
	AbnormalFlags           []ST    `hl7:"8,max=5,len=10,table=0078,display=Abnormal Flags"`
	Probability             NM      `hl7:"9,len=5,display=Probability"`
	NatureOfAbnormalTest    ID      `hl7:"10,len=5,table=0080,display=Nature Of Abnormal Test"`
	ObservResultStatus      ID      `hl7:"11,len=2,table=0085,display=Observ Result Status"`
	DateLastObsNormalValues TS      `hl7:"12,len=19,format=YMDHMS,display=Date Last Obs Normal Values"`
}

func (v OBX) ChildVaries(dtReg map[string]any) (reflect.Value, error) {
	vt, ok := dtReg[v.ValueType]
	if !ok {
		return reflect.Value{}, fmt.Errorf("unknown OBX data type %q", v.ValueType)
	}

	rt := reflect.TypeOf(vt)
	rv := reflect.New(rt)
	return rv.Elem(), nil
}

// Common Order
type ORC struct {
	HL7                   HL7Name `hl7:",name=ORC,type=s"`
	OrderControl          ST      `hl7:"1,required,len=2,table=0119,display=Order Control"`
	PlacerOrder           CM      `hl7:"2,len=75,display=Placer Order #"`
	FillerOrder           CM      `hl7:"3,len=75,display=Filler Order #"`
	PlacerGroup           CM      `hl7:"4,len=75,display=Placer Group #"`
	OrderStatus           ST      `hl7:"5,len=2,table=0038,display=Order Status"`
	ResponseFlag          ST      `hl7:"6,len=1,table=0121,display=Response Flag"`
	TimingQuantity        CM      `hl7:"7,len=200,display=Timing/Quantity"`
	Parent                CM      `hl7:"8,len=200,display=Parent"`
	DateTimeOfTransaction TS      `hl7:"9,len=19,format=YMDHMS,display=Date/Time Of Transaction"`
	EnteredBy             CN      `hl7:"10,len=80,display=Entered By"`
	VerifiedBy            CN      `hl7:"11,len=80,display=Verified By"`
	OrderingProvider      CN      `hl7:"12,len=80,display=Ordering Provider"`
	EnterersLocation      CM      `hl7:"13,len=80,display=Enterer's Location"`
	CallBackPhoneNumber   []TN    `hl7:"14,max=2,len=40,display=Call Back Phone Number"`
}

// Patient Demographics
type PD1 struct {
	HL7   HL7Name `hl7:",name=PD1,type=s"`
	Value ST      `hl7:"1,display=PD1.1"`
}

// Patient Identification
type PID struct {
	HL7                         HL7Name `hl7:",name=PID,type=s"`
	SetIDPatientID              SI      `hl7:"1,len=4,display=Set Id - Patient Id"`
	PatientIDExternalExternalID CK      `hl7:"2,len=16,display=Patient Id External (external Id)"`
	PatientIDInternalInternalID CK      `hl7:"3,required,len=16,display=Patient Id Internal (internal Id)"`
	AlternatePatientID          ST      `hl7:"4,len=12,display=Alternate Patient Id"`
	PatientName                 PN      `hl7:"5,required,len=48,display=Patient Name"`
	MothersMaidenName           ST      `hl7:"6,len=30,display=Mother's Maiden Name"`
	DateOfBirth                 DT      `hl7:"7,len=8,format=YMD,display=Date Of Birth"`
	Sex                         ID      `hl7:"8,len=1,table=0001,display=Sex"`
	PatientAlias                []PN    `hl7:"9,len=48,display=Patient Alias"`
	EthnicGroup                 ID      `hl7:"10,len=1,table=0005,display=Ethnic Group"`
	PatientAddress              AD      `hl7:"11,len=106,display=Patient Address"`
	CountyCode                  ID      `hl7:"12,len=4,display=County Code"`
	PhoneNumberHome             []TN    `hl7:"13,max=3,len=40,display=Phone Number - Home"`
	PhoneNumberBusiness         []TN    `hl7:"14,max=3,len=40,display=Phone Number - Business"`
	LanguagePatient             ST      `hl7:"15,len=25,display=Language - Patient"`
	MaritalStatus               ID      `hl7:"16,len=1,table=0002,display=Marital Status"`
	Religion                    ID      `hl7:"17,len=3,table=0006,display=Religion"`
	PatientAccountNumber        CK      `hl7:"18,len=20,display=Patient Account Number"`
	SsnNumberPatient            ST      `hl7:"19,len=16,display=Ssn Number - Patient"`
	DriversLicNumPatient        CM      `hl7:"20,len=25,display=Driver's Lic Num - Patient"`
}

// Procedures
type PR1 struct {
	HL7                   HL7Name `hl7:",name=PR1,type=s"`
	SetIDProcedure        []SI    `hl7:"1,required,len=4,display=Set Id - Procedure"`
	ProcedureCodingMethod ID      `hl7:"2,required,len=2,table=0089,display=Procedure Coding Method."`
	ProcedureCode         ID      `hl7:"3,required,len=10,table=0088,display=Procedure Code"`
	ProcedureDescription  ST      `hl7:"4,len=40,display=Procedure Description"`
	ProcedureDateTime     TS      `hl7:"5,required,len=19,format=YMDHMS,display=Procedure Date/Time"`
	ProcedureType         ID      `hl7:"6,required,len=2,table=0090,display=Procedure Type"`
	ProcedureMinutes      NM      `hl7:"7,len=4,display=Procedure Minutes"`
	Anesthesiologist      CN      `hl7:"8,len=60,table=0010,display=Anesthesiologist"`
	AnesthesiaCode        ID      `hl7:"9,len=2,table=0019,display=Anesthesia Code"`
	AnesthesiaMinutes     NM      `hl7:"10,len=4,display=Anesthesia Minutes"`
	Surgeon               CN      `hl7:"11,len=60,table=0010,display=Surgeon"`
	ResidentCode          CN      `hl7:"12,len=60,table=0010,display=Resident Code"`
	ConsentCode           ID      `hl7:"13,len=2,table=0059,display=Consent Code"`
}

// Patient Visit
type PV1 struct {
	HL7                     HL7Name `hl7:",name=PV1,type=s"`
	SetIDPatientVisit       SI      `hl7:"1,len=4,display=Set Id - Patient Visit"`
	PatientClass            ID      `hl7:"2,required,len=1,table=0004,display=Patient Class"`
	AssignedPatientLocation ID      `hl7:"3,required,len=12,table=0079,display=Assigned Patient Location"`
	AdmissionType           ID      `hl7:"4,len=2,table=0007,display=Admission Type"`
	PreAdmitNumber          ST      `hl7:"5,len=20,display=Pre-admit Number"`
	PriorPatientLocation    ID      `hl7:"6,len=12,table=0079,display=Prior Patient Location"`
	AttendingDoctor         CN      `hl7:"7,len=60,table=0010,display=Attending Doctor"`
	ReferringDoctor         CN      `hl7:"8,len=60,table=0010,display=Referring Doctor"`
	ConsultingDoctor        []CN    `hl7:"9,len=60,table=0010,display=Consulting Doctor"`
	HospitalService         ID      `hl7:"10,len=3,table=0069,display=Hospital Service"`
	TemporaryLocation       ID      `hl7:"11,len=12,table=0079,display=Temporary Location"`
	PreAdmitTestIndicator   ID      `hl7:"12,len=2,table=0087,display=Pre-admit Test Indicator"`
	ReAdmissionIndicator    ID      `hl7:"13,len=2,table=0092,display=Re-admission Indicator"`
	AdmitSource             ID      `hl7:"14,len=3,table=0023,display=Admit Source"`
	AmbulatoryStatus        ID      `hl7:"15,len=2,table=0009,display=Ambulatory Status"`
	VipIndicator            ID      `hl7:"16,len=2,table=0099,display=Vip Indicator"`
	AdmittingDoctor         CN      `hl7:"17,len=60,table=0010,display=Admitting Doctor"`
	PatientType             ID      `hl7:"18,len=2,table=0018,display=Patient Type"`
	VisitNumber             NM      `hl7:"19,len=4,display=Visit Number"`
	FinancialClass          []ID    `hl7:"20,max=4,len=11,table=0064,display=Financial Class"`
	ChargePriceIndicator    ID      `hl7:"21,len=2,table=0032,display=Charge Price Indicator"`
	CourtesyCode            ID      `hl7:"22,len=2,table=0045,display=Courtesy Code"`
	CreditRating            ID      `hl7:"23,len=2,table=0046,display=Credit Rating"`
	ContractCode            []ID    `hl7:"24,len=2,table=0044,display=Contract Code"`
	ContractEffectiveDate   []DT    `hl7:"25,len=8,format=YMD,display=Contract Effective Date"`
	ContractAmount          []NM    `hl7:"26,len=12,display=Contract Amount"`
	ContractPeriod          []NM    `hl7:"27,len=3,display=Contract Period"`
	InterestCode            ID      `hl7:"28,len=2,table=0073,display=Interest Code"`
	TransferToBadDebtCode   ID      `hl7:"29,len=1,table=0110,display=Transfer To Bad Debt Code"`
	TransferToBadDebtDate   DT      `hl7:"30,len=8,format=YMD,display=Transfer To Bad Debt Date"`
	BadDebtAgencyCode       ST      `hl7:"31,len=10,table=0021,display=Bad Debt Agency Code"`
	BadDebtTransferAmount   NM      `hl7:"32,len=12,display=Bad Debt Transfer Amount"`
	BadDebtRecoveryAmount   NM      `hl7:"33,len=12,display=Bad Debt Recovery Amount"`
	DeleteAccountIndicator  ID      `hl7:"34,len=1,table=0111,display=Delete Account Indicator"`
	DeleteAccountDate       DT      `hl7:"35,len=8,format=YMD,display=Delete Account Date"`
	DischargeDisposition    ID      `hl7:"36,len=2,table=0112,display=Discharge Disposition"`
	DischargedToLocation    ID      `hl7:"37,len=2,table=0113,display=Discharged To Location"`
	DietType                ID      `hl7:"38,len=2,table=0114,display=Diet Type"`
	ServicingFacility       ID      `hl7:"39,len=2,table=0115,display=Servicing Facility"`
	BedStatus               ID      `hl7:"40,len=1,table=0116,display=Bed Status"`
	AccountStatus           ID      `hl7:"41,len=2,table=0117,display=Account Status"`
	PendingLocation         ID      `hl7:"42,len=12,table=0079,display=Pending Location"`
	PriorTemporaryLocation  ID      `hl7:"43,len=12,table=0079,display=Prior Temporary Location"`
	AdmitDateTime           TS      `hl7:"44,len=19,format=YMDHMS,display=Admit Date/Time"`
	DischargeDateTime       TS      `hl7:"45,len=19,format=YMDHMS,display=Discharge Date/Time"`
	CurrentPatientBalance   NM      `hl7:"46,len=12,display=Current Patient Balance"`
	TotalCharges            NM      `hl7:"47,len=12,display=Total Charges"`
	TotalAdjustments        NM      `hl7:"48,len=12,display=Total Adjustments"`
	TotalPayments           NM      `hl7:"49,len=12,display=Total Payments"`
}

// Query Definition
type QRD struct {
	HL7                      HL7Name `hl7:",name=QRD,type=s"`
	QueryDateTime            TS      `hl7:"1,required,len=19,format=YMDHMS,display=Query Date/Time"`
	QueryFormatCode          ID      `hl7:"2,required,len=1,table=0106,display=Query Format Code"`
	QueryPriority            ID      `hl7:"3,required,len=1,table=0091,display=Query Priority"`
	QueryID                  ST      `hl7:"4,required,len=10,display=Query Id"`
	DeferredResponseType     ID      `hl7:"5,len=1,table=0107,display=Deferred Response Type"`
	DeferredResponseDateTime TS      `hl7:"6,len=19,format=YMDHMS,display=Deferred Response Date/Time"`
	QuantityLimitedRequest   CQ      `hl7:"7,required,len=5,table=0126,display=Quantity Limited Request"`
	WhoSubjectFilter         []ST    `hl7:"8,required,len=20,display=Who Subject Filter"`
	WhatSubjectFilter        []ID    `hl7:"9,required,len=3,table=0048,display=What Subject Filter"`
	WhatDepartmentDataCode   []ST    `hl7:"10,required,len=20,display=What Department Data Code"`
	WhatDataCodeValueQual    []ST    `hl7:"11,len=20,display=What Data Code Value Qual."`
	QueryResultsLevel        ID      `hl7:"12,len=1,table=0108,display=Query Results Level"`
}

// Query Filter
type QRF struct {
	HL7                   HL7Name `hl7:",name=QRF,type=s"`
	WhereSubjectFilter    []ST    `hl7:"1,required,len=20,display=Where Subject Filter"`
	WhenDataStartDateTime TS      `hl7:"2,len=19,format=YMDHMS,display=When Data Start Date/Time"`
	WhenDataEndDateTime   TS      `hl7:"3,len=19,format=YMDHMS,display=When Data End Date/Time"`
	WhatUserQualifier     []ST    `hl7:"4,len=20,display=What User Qualifier"`
	OtherQrySubjectFilter []ST    `hl7:"5,len=20,display=Other Qry Subject Filter"`
}

// Ub82 Data
type UB1 struct {
	HL7                       HL7Name `hl7:",name=UB1,type=s"`
	SetIDUb82                 SI      `hl7:"1,len=4,display=Set Id - Ub82"`
	BloodDeductible           ST      `hl7:"2,len=1,display=Blood Deductible"`
	BloodFurnPintsOf40        ST      `hl7:"3,len=2,display=Blood Furn.-pints Of (40)"`
	BloodReplacedPints41      ST      `hl7:"4,len=2,display=Blood Replaced-pints (41)"`
	BloodNotRplcdPints42      ST      `hl7:"5,len=2,display=Blood Not Rplcd-pints(42)"`
	CoInsuranceDays25         ST      `hl7:"6,len=2,display=Co-insurance Days (25)"`
	ConditionCode             []ID    `hl7:"7,max=5,len=2,table=0043,display=Condition Code"`
	CoveredDays23             ST      `hl7:"8,len=3,display=Covered Days - (23)"`
	NonCoveredDays24          ST      `hl7:"9,len=3,display=Non Covered Days - (24)"`
	ValueAmountCode           []CM    `hl7:"10,max=8,len=12,display=Value Amount & Code"`
	NumberOfGraceDays90       ST      `hl7:"11,len=2,display=Number Of Grace Days (90)"`
	SpecProgIndicator44       ID      `hl7:"12,len=2,display=Spec. Prog. Indicator(44)"`
	PsroUrApprovalInd87       ID      `hl7:"13,len=1,display=Psro/Ur Approval Ind. (87)"`
	PsroUrAprvdStayFm88       DT      `hl7:"14,len=8,format=YMD,display=Psro/Ur Aprvd Stay-fm(88)"`
	PsroUrAprvdStayTo89       DT      `hl7:"15,len=8,format=YMD,display=Psro/Ur Aprvd Stay-to(89)"`
	Occurrence2832            []ID    `hl7:"16,max=5,len=20,display=Occurrence (28-32)"`
	OccurrenceSpan33          ID      `hl7:"17,len=2,display=Occurrence Span (33)"`
	OccurrenceSpanStartDate33 DT      `hl7:"18,len=8,format=YMD,display=Occurrence Span Start Date(33)"`
	OccurSpanEndDate33        DT      `hl7:"19,len=8,format=YMD,display=Occur. Span End Date (33)"`
	Ub82Locator2              ST      `hl7:"20,len=30,display=Ub-82 Locator 2"`
	Ub82Locator9              ST      `hl7:"21,len=7,display=Ub-82 Locator 9"`
	Ub82Locator27             ST      `hl7:"22,len=8,display=Ub-82 Locator 27"`
	Ub82Locator45             ST      `hl7:"23,len=17,display=Ub-82 Locator 45"`
}

// Results/update Definition
type URD struct {
	HL7                     HL7Name `hl7:",name=URD,type=s"`
	RUDateTime              TS      `hl7:"1,len=19,format=YMDHMS,display=R/U Date/Time"`
	ReportPriority          ID      `hl7:"2,len=1,table=0109,display=Report Priority"`
	RUWhoSubjectDefinition  []ST    `hl7:"3,required,len=20,display=R/U Who Subject Definition"`
	RUWhatSubjectDefinition []ID    `hl7:"4,len=3,table=0048,display=R/U What Subject Definition"`
	RUWhatDepartmentCode    []ST    `hl7:"5,len=20,display=R/U What Department Code"`
	RUDisplayPrintLocations []ST    `hl7:"6,len=20,display=R/U Display/Print Locations"`
	RUResultsLevel          ID      `hl7:"7,len=1,table=0108,display=R/U Results Level"`
}

// Unsolicited Selection
type URS struct {
	HL7                         HL7Name `hl7:",name=URS,type=s"`
	RUWhereSubjectDefinition    []ST    `hl7:"1,required,len=20,display=R/U Where Subject Definition"`
	RUWhenDataStartDateTime     TS      `hl7:"2,len=19,format=YMDHMS,display=R/U When Data Start Date/Time"`
	RUWhenDataEndDateTime       TS      `hl7:"3,len=19,format=YMDHMS,display=R/U When Data End Date/Time"`
	RUWhatUserQualifier         []ST    `hl7:"4,len=20,display=R/U What User Qualifier"`
	RUOtherResultsSubjectDefini []ST    `hl7:"5,len=20,display=R/U Other Results Subject Defini"`
}
